spring:
  datasource:
    username: root
    password: 333333
    url: jdbc:mysql://127.0.0.1:3306/ry-vue?serverTimezone=UTC&useUnicode=true&characterEncodeing=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
