

server:
  port: 8081

person:
  name: rico
  age: 15
  isHappy: true
  birthday: 1995/05/05
  map: {k1:v1,k2:v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: wangcai
    age: 3

debug: true
